# name: Backend CI

# on:
#   push:
#     paths:
#       - "backend/**"
#   pull_request:
#     paths:
#       - "backend/**"

# jobs:
#   backend:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: backend

#     steps:
#       - uses: actions/checkout@v4

#       - uses: pnpm/action-setup@v3
#         with:
#           version: 9

#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: "pnpm"
#           cache-dependency-path: backend/pnpm-lock.yaml

#       - run: pnpm install
#       - run: pnpm run build
#       - run: pnpm run test
